TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Jonnitto.PhotoSwipe': TRUE
    userInterface:
      translation:
        autoInclude:
          'Jonnitto.PhotoSwipe': ['NodeTypes/*']

Jonnitto:
  PhotoSwipe:
    includeJavascript: TRUE
    includeCSS: Dark  # Light / Dark / FALSE
    preloaderMarkup: '<div class="pswp__preloader__icn"><div class="pswp__preloader__cut"><div class="pswp__preloader__donut"></div></div></div>'
    bgOpacity: 0.8
    alwaysInclude: FALSE
    show:
      topbar: TRUE
      arrows: TRUE
      caption: TRUE
      close: TRUE
      counter: TRUE
      fullscreen: TRUE
      modal: TRUE
      preloader: TRUE
      share: TRUE
      zoom: TRUE
      zoomEffect: TRUE
