Jonnitto:
  PhotoSwipe:
    includeJavascript: true
    includeCSS: Dark
    preloaderMarkup: '<div class="pswp__preloader__icn"><div class="pswp__preloader__cut"><div class="pswp__preloader__donut"></div></div></div>'
    bgOpacity: 0.8
    alwaysInclude: false
    selector:
      onDocument: false
      collection: '[instanceof Neos.Neos:ContentCollection]'
      content: '[instanceof Jonnitto.PhotoSwipe:LightboxMixin][lightbox=true],[instanceof Carbon.Image:Lightbox][lightbox=true],[instanceof Jonnitto.Picture:Lightbox][lightbox=true],[instanceof Jonnitto.Image:Lightbox][lightbox=true],[instanceof Jonnitto.NodeTypes:ImageLightboxMixin][lightbox=true]'
    executeJS: true
    history: true
    selector:
      lightbox: .lightbox
      gallery: body
    show:
      topbar: true
      arrows: true
      caption: true
      close: true
      counter: true
      fullscreen: true
      modal: true
      preloader: true
      share:
        facebook: true
        twitter: true
        pinterest: true
        download: true
      zoom: true
      zoomEffect: true

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.PhotoSwipe:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.PhotoSwipe: true
